import Image from 'next/image'
import React from 'react'

export const metadata = {
    title: "About Us",
    description: "Generated by create REDVision Technologies.",
    author: "REDVision Technologies Pvt. Ltd.",
};

const AboutUs = () => {
    return (
        <section className="lg:px-40 md:px-20 px-6 my-10">
            <div className='my-5 text-center'>
                <h1 className="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span className="text-transparent bg-clip-text bg-gradient-to-r to-red-600 from-yellow-400">Promoters & Directors</span></h1>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-1 mt-10 px-5 md:px-29 items-center">
                <div className='py-10' data-aos="fade-right">
                    <Image src="/images/aboutus.jpg" alt='mobile-app' width={720} height={750} className='m-auto rounded' />
                </div>
                <div className="text-start py-1 lg:py-7 lg:px-5" data-aos="fade-up"
                >
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl">
                        Nikunj Maheswari
                    </h1>
                    <h1 className="mb-2 text-md font-semibold tracking-tight leading-none md:text-5xl lg:text-lg">
                        Promoter and Director
                    </h1>
                    <p className="mb-8 text-md font-normal text-gray-600">
                        With over a decade of extensive experience in the lending industry, Nikunj Maheshwari has
                        cultivated deep expertise in financial services, beginning his career as a Sales Executive and
                        advancing to become a trusted channel partner for leading banks. His journey from humble
                        beginnings in a lower-middle-class family to co-founding a successful non-banking financial
                        company (NBFC) is a testament to his dedication, entrepreneurial spirit, and unwavering
                        commitment to the field of finance.
                        <br />
                        <br />
                        As a passionate first-generation entrepreneur, Nikunj has consistently demonstrated his ability
                        to navigate complex financial landscapes while building lasting relationships across the banking
                        sector. His strategic vision and hands-on leadership continue to drive the growth and success of
                        Prabhat Finance Pvt. Ltd., positioning the company as a significant player in the lending market.
                        With a focus on creating meaningful impact and leaving a lasting legacy in the lending industry,
                        Nikunj remains committed to expanding his influence and footprint in the sector.
                    </p>
                </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-1 px-5 md:px-29 items-center">
                <div className="text-start py-1 lg:py-7 lg:px-5" data-aos="fade-up"
                >
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl">
                        Adheesh Kabra
                    </h1>
                    <h1 className="mb-2 text-md font-semibold tracking-tight leading-none md:text-5xl lg:text-lg">
                        Promoter & Non- Executive Director
                    </h1>
                    <p className="mb-8 text-md font-normal text-gray-600">
                        With a robust entrepreneurial background and over 15 years of rich experience in the financial
                        industry, Adheesh Kabra stands as a paragon of financial acumen.
                        Adheesh's strategic vision led to the founding of Prabhat Investment Services LLP and AS
                        finalysis Venture LLP, where his innovative risk management strategies have significantly
                        benefited Small and Medium Enterprises (SMEs).
                        <br />
                        <br />
                        His exceptional leadership and profound insights into wealth management have earned him the
                        Rajasthan ET Leadership Excellence Award, affirming his status as a top business leader.
                        Adheesh's commitment to excellence and his forward-thinking approach continue to propel
                        Prabhat Finance on a trajectory of sustained growth, solidifying its reputation as a trusted
                        partner in financial empowerment. His roles in the Company encompass strategizing finance,
                        corporate planning, and risk management.
                    </p>
                </div>
                <div className='py-10' data-aos="fade-right">
                    <Image src="/images/aboutus.jpg" alt='mobile-app' width={720} height={750} className='m-auto rounded' />
                </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-1 px-5 md:px-29 items-center">
                <div className='py-10' data-aos="fade-right">
                    <Image src="/images/aboutus.jpg" alt='mobile-app' width={720} height={750} className='m-auto rounded' />
                </div>
                <div className="text-start py-1 lg:py-7 lg:px-5" data-aos="fade-up"
                >
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl">
                        Rishi Agarwal
                    </h1>
                    <h1 className="mb-2 text-md font-semibold tracking-tight leading-none md:text-5xl lg:text-lg">
                        Promoter & Non- Executive Director
                    </h1>
                    <p className="mb-8 text-md font-normal text-gray-600">
                        He is a Fellow Member of the Institute of Chartered Accountants of India and a Chartered
                        Financial Analyst with a Bachelor of Commerce degree from the University of Mumbai. Since
                        2017, he has been with Price Waterhouse Coopers (PwC) as a manager, initially focusing on
                        financial risk consulting and later expanding his expertise to various industries including
                        technology, agro-processing, textiles, oil refining, and wealth management. Mr. Agarwal has led
                        significant projects such as automating financial reporting for a major agro-processing MNC,
                        managing a global finance transformation with 150 stakeholders, and setting up a risk
                        management middle office for Europe's second-largest oil refinery. He brings over eight years of
                        experience in finance, risk, and treasury management, demonstrating a strong track record in
                        digital and financial transformations, and will transition to the role of Executive Director at
                        Prabhat Finance Private Limited after receiving the Certificate of Registration.
                    </p>
                </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-1 px-5 md:px-29 items-center">
                <div className="text-start py-1 lg:py-7 lg:px-5" data-aos="fade-up"
                >
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl">
                        Brij Mohan Baheti
                    </h1>
                    <h1 className="mb-2 text-md font-semibold tracking-tight leading-none md:text-5xl lg:text-lg">
                        Executive Director
                    </h1>
                    <p className="mb-8 text-md font-normal text-gray-600">
                        Mr. Brij Mohan Baheti is a seasoned finance professional with a comprehensive career
                        spanning over four decades. He holds an M.Com in Accountancy and Business Statistics, a
                        Diploma in Banking & Finance, and an MBA in Finance from the University of Rajasthan.
                        Additionally, he is a Certified Associate of the Indian Institute of Bankers.
                        Mr. Baheti began his career at State Bank of India in 1982 and later held pivotal roles at Bank of
                        Rajasthan and ICICI Bank, retiring as Assistant General Manager, Rural and Inclusive Banking,
                        Jaipur Zonal Office. His responsibilities throughout his career have included leadership in
                        branch banking, credit management, and rural banking.
                        <br />
                        <br />
                        Currently, Mr. Baheti is a shareholder and director of Prabhat Finance Private Limited, where he
                        plays a pivotal role in guiding the company's strategy, risk management, operational efficiency,
                        and regulatory compliance. His extensive banking experience, leadership, and strategic insights
                        make him a key contributor to the company's growth and success.
                    </p>
                </div>
                <div className='py-10' data-aos="fade-right">
                    <Image src="/images/aboutus.jpg" alt='mobile-app' width={720} height={750} className='m-auto rounded' />
                </div>
            </div>
        </section>
    )
}

export default AboutUs