import Image from 'next/image'
import React from 'react'

export const metadata = {
    title: "About Us",
    description: "Generated by create REDVision Technologies.",
    author: "REDVision Technologies Pvt. Ltd.",
};

const AboutUs = () => {
    return (
        <section className="lg:px-40 md:px-20 px-6 my-10">
            <div className='my-5 text-center'>
                <h1 className="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span className="text-transparent bg-clip-text bg-gradient-to-r to-red-600 from-yellow-400">Core Values</span></h1>
            </div>
            <div className="gap-1 my-10 px-5 md:px-29">
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className=" text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl uppercase">
                        Customer Focus
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Prioritizing the needs of our clients and striving to exceed their expectations
                        by offering tailored financial solutions and exceptional service.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl uppercase">
                        Transparency
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Maintaining openness and honesty in all interactions, ensuring clear
                        communication and building trust with our stakeholders.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl uppercase">
                        Innovation
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Embracing creativity and technology to develop new financial products and
                        services that address the evolving needs of our clients.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl uppercase">
                        Integrity
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Upholding the highest ethical standards in all business practices, fostering a culture of
                        honesty and accountability.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl uppercase">
                        Reliability
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Consistently delivering dependable and high-quality financial services, ensuring
                        clients can trust and rely on us.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl uppercase">
                        Inclusivity
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Committing to financial inclusion by extending our services to underserved and
                        unserved communities, helping bridge the financial gap.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-2xl uppercase">
                        Community Impact
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Contributing positively to the economic development of the regions we serve, particularly in smaller cities and rural areas.
                    </p>
                </div>
            </div>
        </section>
    )
}

export default AboutUs